# -*- coding: utf-8 -*-
"""TelegramBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h3nHSJn844eHb6_HS6NOXXykoS-wl-GY
"""

import requests

BOT_TOKEN = "8595319737:AAH7BLMP3X1cCoYtoenFGejrw_bZXk1JVKA"

url = f"https://api.telegram.org/bot{BOT_TOKEN}/getUpdates"
response = requests.get(url)

print(response.json())

import requests

BOT_TOKEN = "8595319737:AAH7BLMP3X1cCoYtoenFGejrw_bZXk1JVKA"
CHAT_ID = "5173601195"

message = "Hello Felix 👋 Your Telegram Bot is working!"

url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

payload = {
    "chat_id": CHAT_ID,
    "text": message
}

requests.post(url, data=payload)

print("Message sent!")

import requests

# ===== CONFIG =====
API_KEY = "3de39dbf2140f11a13c917c601aee3eb"
CITIES = ["Nairobi", "Mombasa", "Kisumu"]  # Multiple cities
BOT_TOKEN = "8595319737:AAH7BLMP3X1cCoYtoenFGejrw_bZXk1JVKA"
CHAT_ID = "5173601195"

# ===== FUNCTION TO FETCH WEATHER =====
def get_weather(city):
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    data = requests.get(url).json()

    if data.get("cod") != 200:
        return f"❌ Could not get weather for {city}. Error: {data.get('message')}"

    temp = data["main"]["temp"]
    humidity = data["main"]["humidity"]
    description = data["weather"][0]["description"]
    wind_speed = data["wind"]["speed"]

    # ===== ADVICE LOGIC =====
    if "rain" in description.lower():
        advice = "Carry umbrella ☔"
    elif temp > 30:
        advice = "Hot day. Wear light clothes 🥵"
    elif temp < 15:
        advice = "Cold day. Wear warm clothes 🧥"
    else:
        advice = "Weather looks comfortable 🙂"

    # ===== FORMAT MESSAGE =====
    message = f"""
🌤 *Weather Report - {city}*

🌡 Temperature: {temp}°C
💧 Humidity: {humidity}%
🌥 Condition: {description}
💨 Wind Speed: {wind_speed} m/s

📌 Advice: *{advice}*
"""
    return message

# ===== SEND MESSAGE TO TELEGRAM =====
def send_telegram_message(message):
    telegram_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"
    }
    response = requests.post(telegram_url, data=payload)
    return response.json()

# ===== MAIN LOOP =====
for city in CITIES:
    weather_message = get_weather(city)
    result = send_telegram_message(weather_message)
    print(f"Sent weather for {city}: {result.get('ok')}")

print("✅ All weather notifications sent successfully!")